### ISSUE TITLE
Weird/buggy navbar dropdown behavior in iphone (mobile) safari

### ISSUE THREAD

**Issue by dsshen** [matthew-h-wang/matthew-h-wang.github.io#2]
When I tap "nerts score tracker" from navbar dropdown, sometimes it opens the quixx thing instead. When I tap quixx, it opens "howard is hungry". When I tap "howard is hungry", nothing happens.

When I tap "BCA Teacher Github", nothing happens.

Interestingly, the top item in each dropdown seems to always work properly. `SongSets` link in dropdown always works. Same with `Personal GitHub`. (I lied earlier in text, earlier I though there was some OBO error that was affecting the whole list but it seems like the issues only affect the second item and subsequent items).

Maybe it's something up with dividers.

Issue appears to be intermittent as well.

**Comment by dsshen** [comment]
Also do you need the `Apps & Games` dropdown menu at all? Seems like that list is somewhat redundant with the project cards in the main page.

(It's also not completely redundant either, the dropdown only contains a subset of all the projects on your main page, which means you have to manually update two lists which is a little jank)

**Comment by matthew-h-wang** [comment]
iOS mobile dropdown issue is known: [https://stackoverflow.com/questions/61985187/materialize-css-side-nav-dropdown-wrong-links-on-ios-safari](https://stackoverflow.com/questions/61985187/materialize-css-side-nav-dropdown-wrong-links-on-ios-safari)

This commit should address it: [https://github.com/matthew-h-wang/matthew-h-wang.github.io/commit/4c1421004608d92915b51d1131a493b6ed746bda](https://github.com/matthew-h-wang/matthew-h-wang.github.io/commit/4c1421004608d92915b51d1131a493b6ed746bda)

**Comment by matthew-h-wang** [comment]
`Apps & Games`  and `Projects` are somewhat redundant, but as my number of projects grow, I will update that section to only include more recent/notable projects. Plus, I have some current users (family) who are used to topnav access for certain apps/games.
